m-lab/msak

.github/workflows/coverage.yml, .github/workflows/test.yml, go.mod, internal/measurer/measurer.go, internal/measurer/measurer_test.go, internal/netx/conn.go, pkg/ndt8/model/measurement.go
This PR adds counters for read/written bytes to `netx.Conn` and updates the measurer package to use them to populate `Measurement.BytesSent` and `Measurement.BytesReceived`. 
The main reasons for this change are:
1. Since the measurements channel is buffered, letting the reader fill in its own application-level byte counters meant that there would be a discrepancy (in extreme cases, several seconds long) between the time when the `measurer` queues a new `Measurement` and the time the application-level byte counters are added by the reader. This is avoided by letting the measurer return a fully populated `Measurement` struct that can be directly sent over the wire, even if late.
2. The WebSocket overhead wasn't considered (AFAIK) in the previous NDT implementation, nor was TLS. This method …
=> Add read/written bytes counter to Conn and update measurer

pkg/latency1/model/result.go
Renames the field so that it's in sync with the design document.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/16)
=> Rename Results to RoundTrips

.github/workflows/test.yml, go.mod, go.sum
This PR updates the configuration of GH Actions workflows to use a more recent version of MacOS and Ubuntu. Also, updates go.mod to Go 1.20 to keep it in sync with the version used for testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/20)
=> Update workflow to use macos-12 and ubuntu 22.04

internal/handler/handler.go, internal/netx/conn.go, internal/netx/listener_linux_test.go, pkg/throughput1/protocol.go
This PR adds a method to `netx.ConnInfo` and a `netx.LoadUUID` utility function to save and load a UUID to/from a `context.Context`. This is so that the context key is unique across all packages, being a custom type in `netx`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/17)
=> Add utility functions to netx for saving a UUID in a Context

cmd/msak-server/server.go, internal/latency1/latency1.go, internal/latency1/latency1_test.go, pkg/latency1/model/result.go
This PR uses the mechanism introduced in #17 to save the UUID of each incoming HTTP connection in the request's context. Then, the UUID is retrieved from latency1's  `/authorize` handler, added to the in-memory session and eventually to the archival data. 
This establishes a link between the UDP-based latency1 measurement and the TCP connection that started it, and allows joining the latency1 data with uuid-annotator's annotations in BigQuery.
Stacked on top of #17.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/18)
=> Add UUID to latency1 model

cmd/msak-server/server.go, internal/handler/handler.go, internal/latency1/latency1.go, internal/latency1/latency1_test.go, internal/netx/conn.go, internal/netx/listener_linux_test.go, pkg/latency1/model/result.go, pkg/latency1/spec/spec.go, pkg/throughput1/protocol.go
This PR adds the handlers for `/latency/v1/authorize` and `/latency/v1/result` and starts the UDP server's main loop to process incoming packets.
Stacked on top of #18 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/19)
=> Add latency1 handlers and UDP server to msak-server

internal/latency1/latency1.go
This PR replaces the UUID with the session ID in UDP pings sent in `sendLoop()` and fixes a bug causing pong packets not to be recognized and associated with the correct in-memory session.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/21)
=> Send session ID in packets instead of UUID

cmd/msak-server/server.go
Adds `/latency/v1/authorize` and `/latency/v1/result` to the list of paths managed by the access controller.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/22)
=> Add latency1 paths to access controller

internal/measurer/measurer.go, internal/measurer/measurer_test.go, pkg/throughput1/model/measurement.go, pkg/throughput1/protocol.go, pkg/throughput1/protocol_test.go
This PR adds application-level measurements and namespaces to better separate the two kind of measurements in the Measurement object.
It is a breaking change and will need a schema update.
The client in the https://github.com/m-lab/msak/tree/sandbox-roberto-client branch is compatible with the server in this PR and can be used for local testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/23)
=> Separate network-level and application-level measurements

Dockerfile, cmd/generate-schema/main.go
Adds `latency1` schema to the generate-schema tool and generate `latency1` schema during Docker build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/25)
=> Add latency1 schema to generate-schema tool

build.sh, internal/handler/handler.go, pkg/latency1/model/result.go, pkg/version/version.go
This PR adds a `version` package with a `Version` variable that is meant to be overwritten at compile time. The build script is also updated to set `version.Version` to the correct value, i.e. the current tag (or tag + short commit hash in case we're not at a tag).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/24)
=> Set version via ldflags at compile time

internal/handler/handler_test.go, internal/netx/conn.go, internal/netx/conn_linux.go, internal/netx/conn_stub.go, internal/netx/listener_stub.go, pkg/throughput1/protocol_test.go
This replaces the concrete parameter `*net.TCPConn` of `netx.FromTCPConn` with an equivalent interface. This
- Makes testing easier since we don't need to provide a real `*net.TCPConn`
- Allows `netx.Conn` to wrap other custom `net.Conn`  implementation.
e.g. (quick example not guaranteed to compile :) ):
```golang
// MeteredConn updates a shared atomic counter on reads/writes.
type MeteredConn struct {
*net.TCPConn
bytesRead    *atomic.Uint64
bytesWritten *atomic.Uint64
}
func (mc MeteredConn) Write(b []byte) (int, error) {
n, err := mc.TCPConn.Write(b)
mc.bytesWritten.Add(uint64(n))
return n, err
}
func (mc MeteredConn) Read(b []byte) (int, error) {
n, err := mc.TCPConn.Read(b)
mc.bytesRead.Add(uint64(n))
return n, err
}
// Wrap with netx.Conn.
netxConn := …
```
=> Replace *net.TCPConn with a TCPLikeConn abstraction

cmd/msak-client/client.go, internal/handler/handler.go, internal/handler/handler_test.go, pkg/client/client.go, pkg/client/config.go, pkg/throughput1/protocol.go, pkg/throughput1/protocol_test.go, pkg/throughput1/spec/spec.go
The `bytes` querystring parameter allows the client to specify the maximum number of bytes the server will send/receive before terminating the connection.
The limit is only enabled on the server, since the server is almost always guaranteed to have access to the connection's `TCPInfo`.
The check is implemented in `Protocol.sendCounterflow()` for upload tests (where it checks `TCPInfo.BytesReceived`) and in `Protocol.sender()` for download tests (where it checks `TCPInfo.BytesAcked`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/29)
=> Add support for bytes limit

internal/measurer/measurer.go, internal/measurer/measurer_test.go, pkg/throughput1/protocol.go
This change adds logic to ensure that a final `WireMeasurement` is sent after a byte limit is reached for downloads or uploads.
The changes from https://github.com/m-lab/msak/pull/29 evolved from behaving similarly to https://github.com/m-lab/ndt-server/pull/390 -- where connections are closed after a measurer polling event -- to one where connections are closed after stricter byte limits are sent.
The original approach delayed connection close and could send significantly more data than a user requested / expected. The new approach does not guarantee that the client will receive any polling measurements because the connection may close before any are sent.
This change ensures that at least one measurement is sent after closing the client connection.
NOTE: the message size is not …
=> Send a final WireMeasurement after byte limit reached

README.md, internal/latency1/latency1_test.go, pkg/throughput1/protocol.go
Previously, the server would report that the `applicationBytesSent` was identically the amount requested by the `bytes` limit parameter. However, the client would see more bytes than expected. This was due to the message size being calculated correctly but a new message not being created.
Since `ScaleMessage` is called unconditionally, this change now ensures that a new message is created whenever the scaled `size` is different than the current `messageSize`.
Now the server application data and the client visible application data should differ only by the size of the final measurement message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/33)
=> fix(size): create new message if size changes

pkg/throughput1/protocol.go
Previously, https://github.com/m-lab/msak/pull/30 ensured that before closing the connection a final measurement message was sent to the client. However, that message was not saved in the archival result.
This change ensures that the final measurement is saved to the archival results.
Fixes: https://github.com/m-lab/msak/issues/32
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/34)
=> fix(archive): archive final messages sent to client

cmd/msak-latency/main.go, pkg/latency1/spec/spec.go
Adds a self-contained client for the latency1 protocol.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/35)
=> Add client for the latency1 protocol

pkg/client/client.go, pkg/client/emitter.go
- Fix goodput computation (denominator is `1e6` not `1024*1024`)
- Remove fixed-interval emit loop and align output with incoming messages
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/36)
=> Fix goodput calculation in msak-client

cmd/msak-client/client.go
Previously, msak-client would run both download and upload measurements unconditionally. This change adds two new flags that preserve default behavior but allow for a caller to disable one or the other measurements. This is helpful for users who wish to only test with one or the other.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/37)
=> Add upload and download options

cmd/minimal-download/main.go
Previously, the `minimal-download` client only operated on a single stream. To contrast this tool with other multi stream tools, this change adds a minimal support for multi stream downloads.
The final download rate is currently calculated from the "first-open to first-close" time window.
For example:
```
$ minimal-download -duration 1s -streams 3
Connecting: wss://msak-mlab3-lga04.mlab-oti.measurement-lab.org/throughput/v1/download?...
Download client #1 - Avg  437.05 Mbps, MinRTT  4.55ms, elapsed 0.4319s, application r/w: 0/23595261
Download client #1 - Avg  484.26 Mbps, MinRTT  4.45ms, elapsed 0.8316s, application r/w: 0/50340258
Download client #1 - Avg  483.72 Mbps, MinRTT  4.45ms, elapsed 0.9366s, application r/w: 0/56634811
Download client #1 - Avg  491.40 Mbps, MinRTT  4.45ms, …
```
=> Add minimal, multi stream support to minimal-download client

cmd/minimal-download/main.go, cmd/msak-client/client.go
Closes #41
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/42)
=> Require -streams to be between 1 and 4 in every client

cmd/minimal-download/main.go
This change makes status lines conditional on the number of streams. Previously, single stream results would report two identical results. This is a little confusing, since the results for single streams are identical. This change reports a single summary for single stream and multiple summaries for multi stream tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/43)
=> fix: single status line for one stream

cmd/msak-client/client.go, pkg/client/client.go, pkg/client/emitter.go
This PR adds a summary at the end of the measurement and fixes the RTT calculations.
Closes #40
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/45)
=> Add summary at the end of the measurement and fix RTT calc

README.md
The existing link doesn't seem to give access unless the users have edit permissions on the document. This one works even if logged out from any Google account.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/46)
=> Fix design document link

pkg/throughput1/spec/spec.go
This allows the CellWatch test, consisting of a warm-up phase that can last up to 10s + an active test phase that lasts for 10s, to always complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/msak/48)
=> Set MaxRuntime to 25s
